pengarwin_vendor:
    path:      /vendor.{_format}
    defaults:  { _controller: PengarWinCoreBundle:Vendor:index, _format: html}
    methods:   [GET,POST]
    requirements:
         _format: (html|json)

pengarwin_vendor_new:
    path:      /vendor/new
    defaults:  { _controller: PengarWinCoreBundle:Vendor:new }
    methods:   [GET,POST]

pengarwin_vendor_show:
    path:      /vendor/{slug}
    defaults:  { _controller: PengarWinCoreBundle:Vendor:show }

pengarwin_vendor_edit:
    path:      /vendor/{slug}/edit.{_format}
    defaults:  { _controller: PengarWinCoreBundle:Vendor:edit, _format: html}
    methods:   [GET,POST]
    requirements:
         _format: (html|json)


pengarwin_journal_post:
    path:      /accounts/{path}/post-journal/{id}
    defaults:  { _controller: PengarWinCoreBundle:Journal:post }
    methods:   [POST]
    requirements:
        _method: POST
        path:       .+
        journal_id: \d+


pengarwin_account:
    path:      /accounts.{_format}
    defaults:  { _controller: PengarWinCoreBundle:Account:index, _format: html }
    methods:   [GET,POST]
    requirements:
         _format: (html|json)

pengarwin_account_show:
    path:      /accounts/{path}
    defaults:  { _controller: PengarWinCoreBundle:Account:show }
    requirements:
        path: .+


pengarwin_homepage:
    path:      /
    defaults:  { _controller: PengarWinCoreBundle:Default:index }
