pengarwin_vendor:
    path:      /vendor
    defaults:  { _controller: PengarWinCoreBundle:Vendor:index }

pengarwin_vendor_show:
    path:      /vendor/{slug}
    defaults:  { _controller: PengarWinCoreBundle:Vendor:show }


pengarwin_journal_post:
    path:      /accounts/{path}/post-journal/{id}
    defaults:  { _controller: PengarWinCoreBundle:Journal:post }
    requirements:
        _method: post
        path:       .+
        journal_id: \d+


pengarwin_account:
    path:      /accounts
    defaults:  { _controller: PengarWinCoreBundle:Account:index }

pengarwin_account_show:
    path:      /accounts/{path}
    defaults:  { _controller: PengarWinCoreBundle:Account:show }
    requirements:
        path: .+


pengarwin_homepage:
    path:      /
    defaults:  { _controller: PengarWinCoreBundle:Default:index }
