phospr_vendor:
    path:      /vendor.{_format}
    defaults:  { _controller: PhosprCoreBundle:Vendor:index, _format: html}
    methods:   [GET,POST]
    requirements:
         _format: (html|json)

phospr_vendor_new:
    path:      /vendor/new
    defaults:  { _controller: PhosprCoreBundle:Vendor:new }
    methods:   [GET,POST]

phospr_vendor_show:
    path:      /vendor/{slug}
    defaults:  { _controller: PhosprCoreBundle:Vendor:show }

phospr_vendor_edit:
    path:      /vendor/{slug}/edit.{_format}
    defaults:  { _controller: PhosprCoreBundle:Vendor:edit, _format: html}
    methods:   [GET,POST]
    requirements:
         _format: (html|json)


phospr_journal_show:
    path:      /journals/{id}.{_format}
    defaults:  { _controller: PhosprCoreBundle:Journal:show, _format: html }
    methods:   [GET]
    requirements:
        id: \d+

phospr_journal_edit:
    path:      /journal/{id}/edit
    defaults:  { _controller: PhosprCoreBundle:Journal:edit }
    methods:   [GET,POST]
    requirements:
        id: \d+

phospr_journal_post:
    path:      /accounts/{path}/post-journal/{id}
    defaults:  { _controller: PhosprCoreBundle:Journal:post }
    methods:   [POST]
    requirements:
        _method: POST
        path:       .+
        journal_id: \d+


phospr_account:
    path:      /accounts.{_format}
    defaults:  { _controller: PhosprCoreBundle:Account:index, _format: html }
    methods:   [GET,POST]
    requirements:
         _format: (html|json)

phospr_account_show:
    path:      /accounts/{path}
    defaults:  { _controller: PhosprCoreBundle:Account:show }
    requirements:
        path: .+


phospr_homepage:
    path:      /
    defaults:  { _controller: PhosprCoreBundle:Default:index }
