parameters:
    phospr.account_handler.class: Phospr\DoubleEntryBundle\Model\AccountHandler
    phospr.vendor_param_converter.class: Phospr\CoreBundle\Request\ParamConverter\VendorParamConverter

services:
    phospr.account_handler:
        class:     %phospr.account_handler.class%

    phospr.vendor_param_converter:
        class:     %phospr.vendor_param_converter.class%
        arguments:
            - @doctrine.orm.entity_manager
            - @phospr.organization_handler
        tags:
            - { name: request.param_converter, converter: vendor, priority: 10 }
